blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'
urlpatterns = [
    # blog/
    path('', views.PostLV.as_view(), name='index'),
    # blog/post/
    path('post/', views.PostLV.as_view(), name='post_list'),
    # blog/post/django-example
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),
    # blog/archive/
    path('archive/', views.PostAV.as_view(), name='post_archive'),
    # blog/archive/2019/
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),
    # blog/archive/2019/nov/
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),
    # blog/archive/2019/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),
    # blog/archive/today/
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),
    # blog/tag/
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    # blog/tag/tagname/
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),
    # blog/search/
    path('search/', views.SearchFormView.as_view(), name='search'),
    # blog/add/
    path('add/', views.PostCreateView.as_view(), name='add'),
    # blog/change/
    path('change/', views.PostChangeLV.as_view(), name='change'),
    # blog/99/update/
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='update'),
    # blog/99/delete/
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from bookmark.views import BookmarkLV, BookmarkDV
from mysite.views import HomeView, UserCreateView, UserCreateDoneTV

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),

]

blog/models.py
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager
from django.contrib.auth.models import User
from django.utils.text import slugify

# Create your models here.
class Post(models.Model):
    title = models.CharField(verbose_name='TITLE', max_length=50)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for title alias.')
    description = models.CharField('DESCRIPTION', max_length=100, blank=True, help_text='simple description text.')
    content = models.TextField('CONTENT')
    create_dt = models.DateTimeField('CREATE DATE', auto_now_add=True)
    modify_dt = models.DateTimeField('MODIFY DATE', auto_now=True)

    tags = TaggableManager(blank=True)

    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, verbose_name='OWNER')

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'blog_posts'
        ordering = ('-modify_dt',)
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("blog:post_detail", args=(self.slug,))
    
    def get_previous(self):
        return self.get_previous_by_modify_dt()
    
    def get_next(self):
        return self.get_next_by_modify_dt()
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True)
        return super().save(*args, **kwargs)

blog/forms.py
from django import forms

class PostSearchForm(forms.Form):
    search_word = forms.CharField(label='Search Word')

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, TemplateView, FormView, CreateView, DeleteView, UpdateView
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView
from django.views.generic.dates import DayArchiveView, TodayArchiveView
from blog.models import Post
from blog.forms import PostSearchForm
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from mysite.urls import OwnerOnlyMixin

  
# Create your views here.
class PostLV(ListView):
    model = Post
    template_name = 'blog/post_all.html'
    context_object_name = 'posts'
    paginate_by = 2

class PostDV(DetailView):
    model = Post

class PostAV(ArchiveIndexView):
    model = Post
    date_field = 'modify_dt'

class PostYAV(YearArchiveView):
    model = Post
    date_field = 'modify_dt'
    make_object_list = True

class PostMAV(MonthArchiveView):
    model = Post 
    date_field = 'modify_dt'

class PostDAV(DayArchiveView):
    model = Post
    date_field = 'modify_dt'

class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'modify_dt'

class TagCloudTV(TemplateView):
    template_name = 'taggit/taggit_cloud.html'

class TaggedObjectLV(ListView):
    template_name = 'taggit/taggit_post_list.html'
    model = Post

    def get_queryset(self):
        return Post.objects.filter(tags__name=self.kwargs.get('tag'))
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tagname"] = self.kwargs['tag']
        return context

class SearchFormView(FormView):
    form_class = PostSearchForm
    template_name = 'blog/post_search.html'

    def form_valid(self, form):
        searchWord = form.cleaned_data['search_word']
        post_list = Post.objects.filter(Q(title__icontains=searchWord)|Q(description__icontains=searchWord)|Q(content__icontains=searchWord)).distinct()

        context = {}
        context['form'] = form
        context['search_term'] = searchWord
        context['object_list'] = post_list

        return render(self.request, self.template_name, context)

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'slug', 'description', 'content', 'tags']
    initial = {'slug':'auto-filling-do-not-input'}
    success_url = reverse_lazy('blog:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)
    
class PostChangeLV(LoginRequiredMixin, ListView):
    template_name = 'blog/post_change_list.html'

    def get_queryset(self):
        return Post.objects.filter(owner=self.request.user)

class PostUpdateView(OwnerOnlyMixin, UpdateView):
    model = Post
    fields = ['title', 'slug', 'description', 'content', 'tags']
    success_url = reverse_lazy('blog:index')

class PostDeleteView(OwnerOnlyMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:index')

    
    

templates/blog/post_all.html
{% extends 'base.html'%}

{% block title %}
post_all.html
{% endblock %}

{% block content %}
    <h1>Blog List</h1>
    <br>

    {% for post in posts %}
    <h3><a href="{{ post.get_absolute_url }}">{{post.title}}</a></h3>
    {{post.modify_dy|date:"N d, Y"}}
    <p>{{post.description}}</p>
    {% endfor %}
    <br>

    <div>
        <span>
            {%if page_obj.has_previous%}
            <a href="=?page={{page_obj.previous_page_number}}">PreviousPage</a>
            {%endif%}

            Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}

            {%if page_obj.has_next%}
            <a href="=?page={{page_obj.next_page_number}}">NextPage</a>
            {%endif%}
        </span>
    </div>
{% endblock %}

templates/blog/post_archive.html
{% extends 'base.html'%}

{% block title %}
post_archive.html
{% endblock %}

{% block content %}
    <h1>Post Archives until {% now "N d, Y" %}</h1>
    <br>

    <ul>
        {% for date in date_list %}
        <li style="display: inline;">
            <a href="{% url 'blog:post_year_archive' date|date:'Y' %}">Year{{ date|date:"Y" }}</a>
        </li>
        {% endfor %}
    </ul>
    <br>
    <div>
        <ul>
            {% for post in object_list %}
            <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
                <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
            </li>
            {% endfor %}
        </ul>
    </div>


{% endblock %}

templates/blog/post_archive_day.html
{% extends 'base.html'%}

{% block title %}
post_archive_today.html
{% endblock %}

{% block content %}
    <h1>Post Archives for {{ day|date:"N d, Y" }}</h1>
    <br>

    <div>
        <ul>
            {% for post in object_list %}
            <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
                <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
            </li>
            {% endfor %}
        </ul>
    </div>


{% endblock %}

templates/blog/post_archive_month.html
{% extends 'base.html'%}

{% block title %}
post_archive_{{month|date:"N, Y"}}.html
{% endblock %}

{% block content %}
    <h1>Post Archives for {{ month|date:"N, Y" }}</h1>
    <br>

    <div>
        <ul>
            {% for post in object_list %}
            <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
                <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
            </li>
            {% endfor %}
        </ul>
    </div>


{% endblock %}

templates/blog/post_archive_year.html
{% extends 'base.html'%}

{% block title %}
post_archive_{{year|date:"Y"}}.html
{% endblock %}

{% block content %}
    <h1>Post Archives for {{ year|date:"Y" }}</h1>
    <br>

    <ul>
        {% for date in date_list %}
        <li style="display: inline;">
            <a href="{% url 'blog:post_month_archive' year|date:'Y' date|date:'b' %}">{{ date|date:"F" }}</a>
        </li>
        {% endfor %}
    </ul>
    <br>
    <div>
        <ul>
            {% for post in object_list %}
            <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
                <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
            </li>
            {% endfor %}
        </ul>
    </div>


{% endblock %}

templates/blog/post_detail.html
{% extends 'base.html'%}

{% block title %}
post_detail.html
{% endblock %}

{% block content %}
    <h1>{{ object.title }}</h1>
    <br>

    <p>
        {% if object.get_previous %}
        <a href="{{ object.get_previous.get_absolute_url }}" title="View previous Post">
            &laquo; -- {{object.get_previous}}
        </a>
        {% endif %}

        {% if object.get_next %}
        <a href="{{ object.get_next.get_absolute_url }}" title="View next Post">
            {{object.get_next}} -- &raquo;
        </a>
        {% endif %}       
    </p>

    <p>
        {{object.modify_dt|date:"j F Y"}}
    </p>

    <div>
        {{ object.content|linebreaks }}
    </div>

    <br>
    <div>
        <b>Tags</b><i class="fas fa-tag"></i>
        {% load taggit_templatetags2_tags %}
        {% get_tags_for_object object as 'tags' %}
        {% for tag in tags %}
        <a href="{% url 'blog:tagged_object_list' tag.name %}">{{ tag.name }}</a>
        {% endfor %}
        &emsp;
        <a href="{% url 'blog:tag_cloud' %}"><span class="btn btn-info btn-sm">TagCloud</span></a>
    </div>

{% endblock %}

templates/blog/post_search.html
{% extends 'base.html'%}

{% block title %}
post_search_{{ search.term }}.html
{% endblock %}

{% block content %}
    <h1>Blog Search</h1>
    <br>

    <form action="." method="post">{% csrf_token %}
        {{ form|as_table }}
        <input type="submit" value="Submit" class="btn btn-primary btn-sm">
    </form>
    <br><br>
    {% if object_list %}
        {% for post in object_list %}
        <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
        {{post.modify_dt|date:"N d, Y"}}
        <p>{{ post.description }}</p>
        {% endfor %}
    {% elif search_term %}
        <b>Search word({{search_term}}) Not Found</b>
    {% endif %}

{% endblock %}