blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'
urlpatterns = [
    # blog/
    path('', views.PostLV.as_view(), name='index'),
    # blog/post/
    path('post/', views.PostLV.as_view(), name='post_list'),
    # blog/post/django-example
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),
    # blog/archive/
    path('archive/', views.PostAV.as_view(), name='post_archive'),
    # blog/archive/2019/
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),
    # blog/archive/2019/nov/
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),
    # blog/archive/2019/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),
    # blog/archive/today/
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),
    # blog/tag/
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    # blog/tag/tagname/
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),
    # blog/search/
    path('search/', views.SearchFormView.as_view(), name='search'),
    # blog/add/
    path('add/', views.PostCreateView.as_view(), name='add'),
    # blog/change/
    path('change/', views.PostChangeLV.as_view(), name='change'),
    # blog/99/update/
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='update'),
    # blog/99/delete/
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),
]

bookmark/urls.py
from django.urls import path, include
from bookmark import views

app_name = 'bookmark'

urlpatterns = [
    path('', views.BookmarkLV.as_view(), name='index'),
    path('<int:pk>/', views.BookmarkDV.as_view(), name='detail'),
    path('add/', views.BookmarkCreateView.as_view(), name='add'),
    path('change/', views.BookmarkChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', views.BookmarkUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.BookmarkDeleteView.as_view(), name='delete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from bookmark.views import BookmarkLV, BookmarkDV
from mysite.views import HomeView, UserCreateView, UserCreateDoneTV

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),

]

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>

    {% block extra-style %}{% endblock %}
  </head>
  <body style="padding-top:90px;">
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
        <span class="navbar-brand mx-5 mb-0 font-weight-bold font-italic">Django - Python Web Programming</span>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item mx-1 btn btn-primary">
                    <a class="nav-link text-white" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item mx-1 btn btn-primary">
                    <a class="nav-link text-white" href="{% url 'bookmark:index' %}">Bookmark</a>
                </li>
                <li class="nav-item mx-1 btn btn-primary">
                    <a class="nav-link text-white" href="{% url 'blog:index' %}">Blog</a>
                </li>
                <li class="nav-item mx-1 btn btn-primary">
                    <a class="nav-link text-white" href="#">Photo</a>
                </li>
                <li class="nav-item dropdown mx-1 btn btn-primary">
                    <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Util
                    </a>
                    <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'blog:post_archive' %}">Archive</a>
                    <a class="dropdown-item" href="{% url 'blog:search' %}">Search</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0" action='' method="post">{% csrf_token %}
                <input class="form-control mr-sm-2" type="search" placeholder="Search" name='search_word'>
            </form>
            <ul class="navbar-nav ml-5 mr-5">
                <li class="nav-item dropdown mx-1 btn btn-primary">
                    {% if user.is_active%}
                        <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" data-toggle="dropdown">
                            <i class="fas fa-user"></i>&ensp;{% firstof user.get_short_name user.get_username %}&ensp;
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                            <a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
                        </div>
                    {% else %}
                        <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" data-toggle="dropdown">
                            <i class="fas fa-user"></i>&ensp;Anonymous&ensp;
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'login' %}">Login</a>
                            <a class="dropdown-item" href="{% url 'register' %}">Register</a>
                        </div>
                    {% endif %}
                </li>
            </ul>
        </div>
    </nav>

    <div class="container">
        {% block content %}{% endblock %}
    </div>

    {% block footer %}{% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/3a51ebe593.js" crossorigin="anonymous"></script>

    {% block extra-script %}{% endblock %}
  </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Django Web Programming{% endblock %}

{% block extra-style %}
    <style>
        .home-image{
            background-image: url('{% static 'img/lion.jpg' %}');
            background-repeat: no-repeat;
            background-position: center;
            background-size: 100%;
            height: 500px;
            border-top: 10px solid #ccc;
            border-bottom: 10px solid #ccc;
            padding: 20px 0 0 20px;
        }
        .title{
            color: #c80;
            font-weight: bold;
        }
        .powered{
            position: relative;
            top: 77%;
            color: #cc0;
            font-style: italic;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="home-image">
        <h2 class="title">Django - Python Web Programming</h2>
        <h4 class="powered"><i class="fas fa-arrow-circle-right"></i> powered by django and bootstrap.</h4>
    </div>

    <hr style="margin:10px 0;">

    <div class="row text-center">
        <div class="col-sm-6">
            <h3>Bookmark App</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sit amet mollis nulla. Vivamus nec tempus ligula. Curabitur eget orci vitae metus mattis sodales. Sed efficitur sed justo eu iaculis. Donec feugiat posuere venenatis. Mauris id enim vel mauris dapibus bibendum eget non nisl. Vestibulum sit amet metus augue. Mauris eget egestas quam. Morbi hendrerit aliquet ipsum ut volutpat. Suspendisse pretium metus ultrices elementum mollis. Curabitur egestas id justo non scelerisque.</p>
        </div>
        <div class="col-sm-6">
            <h3>Blog App</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sit amet mollis nulla. Vivamus nec tempus ligula. Curabitur eget orci vitae metus mattis sodales. Sed efficitur sed justo eu iaculis. Donec feugiat posuere venenatis. Mauris id enim vel mauris dapibus bibendum eget non nisl. Vestibulum sit amet metus augue. Mauris eget egestas quam. Morbi hendrerit aliquet ipsum ut volutpat. Suspendisse pretium metus ultrices elementum mollis. Curabitur egestas id justo non scelerisque.</p>
        </div>
    </div>
{% endblock %}

{% block footer %}
    <footer class="fixed-bottom bg-info">
        <div class="text-white font-italic text-right mr-5">Copyright &copy; 2023 DjangoBook by Kim</div>
    </footer>
{% endblock %}